// main.js — Othello logic + firebase realtime sync (full with Othello flipping) import { ref, push, set, onValue, remove, update, onDisconnect, get } from 'https://www.gstatic.com/firebasejs/9.22.2/firebase-database.js'; import { db } from './firebase.js';

// --- Helpers & DOM const $ = sel => document.querySelector(sel); const playerNameInput = $('#playerName'); const createRoomBtn = $('#createRoom'); const refreshRoomsBtn = $('#refreshRooms'); const roomsList = $('#roomsList'); const roomLinkEl = $('#roomLink'); const roomIdEl = $('#roomId'); const copyLinkBtn = $('#copyLink'); const leaveRoomBtn = $('#leaveRoom'); const randomJoinBtn = $('#randomJoin'); const chatLog = $('#chatLog'); const chatInput = $('#chatInput'); const boardCanvas = $('#board'); const ctx = boardCanvas.getContext('2d'); const turnInfo = $('#turnInfo'); const playersInfo = $('#players'); const timerEl = $('#timer'); const statusEl = $('#status');

// --- Game state let localPlayerId = 'p_' + Math.random().toString(36).slice(2,9); let localName = ''; let currentRoom = null; let gameRef = null; let roomRef = ref(db, 'rooms'); let moveTimerEnabled = true; const SIZE = 8; let cellSize = Math.floor(boardCanvas.width / SIZE);

// --- Helper functions function emptyBoard(){ const b = Array.from({length:SIZE},()=>Array.from({length:SIZE},()=>null)); b[3][3]='W'; b[3][4]='B'; b[4][3]='B'; b[4][4]='W'; return b; }

function drawBoard(board){ ctx.clearRect(0,0,boardCanvas.width,boardCanvas.height); ctx.fillStyle = '#144729'; ctx.fillRect(0,0,boardCanvas.width,boardCanvas.height); for(let r=0;r<SIZE;r++){ for(let c=0;c<SIZE;c++){ let x=ccellSize, y=rcellSize; ctx.strokeStyle='#072b18'; ctx.lineWidth=2; ctx.strokeRect(x+1,y+1,cellSize-2,cellSize-2); const v=board[r][c]; if(v){ ctx.beginPath(); ctx.arc(x+cellSize/2,y+cellSize/2,cellSize0.38,0,Math.PI2); ctx.fillStyle=v==='B'?'#000':'#fff'; ctx.shadowColor='#000a';ctx.shadowBlur=6; ctx.fill();ctx.shadowBlur=0; ctx.closePath(); } } } }

function getRoomFromUrl(){ const p=new URLSearchParams(location.search); return p.get('room'); }

// --- Firebase lobby actions async function refreshLobby(){ onValue(roomRef, snap => { const data=snap.val()||{}; roomsList.innerHTML=''; const open=Object.keys(data).filter(k=>!data[k].closed); if(open.length===0) roomsList.innerHTML='No open rooms'; open.forEach(k=>{ const room=data[k]; const el=document.createElement('div'); el.className='roomItem'; el.innerHTML=Room <b>${k}</b> — ${Object.keys(room.players||{}).length}/2 <button data-room='${k}'>Join</button>; el.querySelector('button').onclick=()=>joinRoom(k); roomsList.appendChild(el); }); }); }

async function createRoom(){ localName = playerNameInput.value.trim() || ('Guest_'+localPlayerId.slice(-4)); const r = push(roomRef); const id = r.key; const roomObj = { created: Date.now(), board: emptyBoard(), currentTurn: 'B', players: { [localPlayerId]: { name: localName, color: 'B' } }, chat: {}, closed: false }; await set(ref(db, 'rooms/'+id), roomObj); onDisconnect(ref(db,'rooms/'+id+'/players/'+localPlayerId)).remove(); enterRoom(id); }

async function joinRoom(id){ localName = playerNameInput.value.trim() || ('Guest_'+localPlayerId.slice(-4)); const pRef = ref(db, 'rooms/'+id+'/players'); const snap = await get(pRef); const players = snap.val() || {}; if(Object.keys(players).length>=2){ alert('Room full'); return; } const assignedColor = Object.values(players).some(pl=>pl.color==='B')?'W':'B'; await update(ref(db,'rooms/'+id+'/players/'+localPlayerId), {name:localName,color:assignedColor}); onDisconnect(ref(db,'rooms/'+id+'/players/'+localPlayerId)).remove(); enterRoom(id); }

async function randomJoin(){ const snap=await get(roomRef); const data=snap.val()||{}; const open=Object.entries(data).find(([k,v])=>!v.closed&&Object.keys(v.players||{}).length<2); if(open) return joinRoom(open[0]); return createRoom(); }

function enterRoom(id){ currentRoom=id; roomIdEl.textContent=id; roomLinkEl.classList.remove('hidden'); history.replaceState(null,'','?room='+id); gameRef=ref(db,'rooms/'+id); bindRoomListeners(); }

function leaveRoom(){ if(!currentRoom) return; remove(ref(db,'rooms/'+currentRoom+'/players/'+localPlayerId)); currentRoom=null;gameRef=null; roomLinkEl.classList.add('hidden'); history.replaceState(null,'',location.pathname); }

// --- Room listeners function bindRoomListeners(){ if(!gameRef) return; onValue(gameRef, snap => { const room=snap.val(); if(!room){statusEl.textContent='Room closed';return;} drawBoard(room.board); turnInfo.textContent='Turn: '+room.currentTurn; playersInfo.textContent='Players: '+Object.values(room.players||{}).map(p=>p.name+'('+p.color+')').join(', '); chatLog.innerHTML=''; if(room.chat){Object.values(room.chat).forEach(m=>{const d=document.createElement('div');d.textContent=m.from+': '+m.text;chatLog.appendChild(d);});} }); }

// --- Chat chatInput.addEventListener('keypress',async e=>{ if(e.key==='Enter'&&currentRoom){ const text=chatInput.value.trim();if(!text)return;chatInput.value=''; const cRef=push(ref(db,'rooms/'+currentRoom+'/chat')); await set(cRef,{from:playerNameInput.value||localPlayerId,text,t:Date.now()}); } });

// --- Othello rules: directions and flipping const dirs=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]]; function validMoves(board,color){ const opponent=color==='B'?'W':'B'; const moves=[]; for(let r=0;r<SIZE;r++){ for(let c=0;c<SIZE;c++){ if(board[r][c])continue; for(const [dr,dc]of dirs){ let rr=r+dr,cc=c+dc,foundOpp=false; while(rr>=0&&rr<SIZE&&cc>=0&&cc<SIZE&&board[rr][cc]===opponent){foundOpp=true;rr+=dr;cc+=dc;} if(foundOpp&&rr>=0&&rr<SIZE&&cc>=0&&cc<SIZE&&board[rr][cc]===color){moves.push([r,c]);break;} } } } return moves; }

function applyMove(board,r,c,color){ const opponent=color==='B'?'W':'B'; let flipped=false; for(const[dr,dc]of dirs){ let line=[];let rr=r+dr,cc=c+dc; while(rr>=0&&rr<SIZE&&cc>=0&&cc<SIZE&&board[rr][cc]===opponent){line.push([rr,cc]);rr+=dr;cc+=dc;} if(line.length>0&&rr>=0&&rr<SIZE&&cc>=0&&cc<SIZE&&board[rr][cc]===color){ for(const[pR,pC]of line){board[pR][pC]=color;} flipped=true; } } if(flipped){board[r][c]=color;} return flipped; }

boardCanvas.addEventListener('click', async ev=>{ if(!currentRoom) return; const rect=boardCanvas.getBoundingClientRect(); const x=Math.floor((ev.clientX-rect.left)/cellSize); const y=Math.floor((ev.clientY-rect.top)/cellSize); const snap=await get(gameRef); const room=snap.val(); const myColor=(room.players[localPlayerId]||{}).color; if(room.currentTurn!==myColor) return; const board=room.board; if(board[y][x])return; const moves=validMoves(board,myColor); if(!moves.some(([r,c])=>r===y&&c===x))return; applyMove(board,y,x,myColor); const next=room.currentTurn==='B'?'W':'B'; await update(gameRef,{board,currentTurn:next}); document.getElementById('sndPlace').play().catch(()=>{}); });

// --- UI binding createRoomBtn.onclick=createRoom; refreshRoomsBtn.onclick=refreshLobby; randomJoinBtn.onclick=randomJoin; leaveRoomBtn.onclick=leaveRoom; copyLinkBtn.onclick=()=>{navigator.clipboard.writeText(location.href);alert('Link copied');}; $('#moveTimerToggle').addEventListener('change',e=>moveTimerEnabled=e.target.checked); window.addEventListener('load',()=>{const r=getRoomFromUrl();refreshLobby();if(r)joinRoom(r);});